# Generated by Django 3.2.7 on 2021-10-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211014_1628'),
        ('foods', '0002_alter_product_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
    ]
