# Generated by Django 3.2.7 on 2021-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211019_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
