# Generated by Django 3.2.7 on 2021-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
