# Generated by Django 3.2.7 on 2021-10-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211021_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/%Y/%m/%d'),
        ),
    ]
